Repository Model-UN/cimun-web, pull requests merged in 2021-06, with the labels that each got.

#11 Feature/1 deployment
  pages/index.js
Labels: help wanted

#20 Dev/2 vercel sponsorship
  .gitignore
  LICENSE
  README.md
  package-lock.json
  package.json
  pages/index.js
  public/vercel-banner.svg
  styles/Home.module.css
Labels: enhancement

#21 Dev/2 vercel sponsorship (#20)
  .gitignore
  LICENSE
  README.md
  package-lock.json
  package.json
  pages/index.js
  public/vercel-banner.svg
  styles/Home.module.css
Labels: enhancement, operations

#22 Create Jumbotron Component
  components/jumbotron/Jumbotron.module.css
  components/jumbotron/index.tsx
  pages/index.js
  pages/index.tsx
  styles/Home.module.css
  styles/colors.ts
  styles/fonts.ts
  styles/globals.css
Labels: enhancement

#24 Setup Styled Components
  components/jumbotron/Jumbotron.module.css
  components/jumbotron/index.tsx
  package.json
  pages/index.tsx
  styles/Home.module.css
  styles/containers.ts
  styles/typography.ts
  yarn.lock
Labels: enhancement

#31 Dev/2b vercel sponsorship
  README.md
Labels: documentation

#30 Dev/2b vercel sponsorship
  README.md
Labels: documentation

#29 Dev/2b vercel sponsorship
  README.md
Labels: documentation

#32 Header Nav Component
  components/headerNav/index.tsx
  components/jumbotron/index.tsx
  pages/about/index.tsx
  pages/conference/index.tsx
  pages/index.tsx
  public/cimun-logo.png
  styles/breakpoints.js
  styles/colors.ts
  styles/containers.ts
  yarn.lock
Labels: enhancement
